### ISSUE TITLE
时间区间查询出错

### ISSUE THREAD

**Issue by songjinghe** [TGraphDB/temporal-storage#12]
```java
@Test
    public void tCypherTest(){
//        System.out.println(System.getProperty("java.vm.name"));
//        System.out.println(System.getProperty("java.vm.info"));
//        System.exit(0);
        GraphDatabaseService db = new GraphDatabaseFactory().newEmbeddedDatabase(new File("/media/song/test/db-network-only-ro"));
        Runtime.getRuntime().addShutdownHook(new Thread(db::shutdown));
        long t = System.currentTimeMillis();
        try (Transaction tx = db.beginTx()) {
//            for(int i=0; i<10; i++) {
//                System.out.println(db.execute("MATCH ()-[r:ROAD_TO]->() WHERE id(r)=1 SET r.travel_time_100"+i+"="+(30+i)).resultAsString());
                db.execute("MATCH ()-[r:ROAD_TO]->() WHERE id(r)=1 SET r.travel_time=TV(3~13:30, 100~NOW:2)");
//            }
            tx.success();
        }
        System.out.println(System.currentTimeMillis() - t);
        try (Transaction tx = db.beginTx()) {
            for(int i=0; i<102; i++) {
                System.out.println(db.getRelationshipById(1).getTemporalProperty("travel_time", i));
//                System.out.println(db.execute("MATCH ()-[r:ROAD_TO]->() WHERE r.id=1 SET r.travel_time_100="+(30+i)).resultAsString());
            }
//            System.out.println(db.execute("MATCH ()-[r:ROAD_TO]->() WHERE r.id=1 SET r.travel_time=TV(100~NOW:30)").resultAsString());
            tx.success();
        }
        System.out.println(System.currentTimeMillis() - t);
        try(Transaction tx = db.beginTx()){
            Relationship r = db.getRelationshipById(1);
            for(String key : r.getPropertyKeys()){
                System.out.println(key+": "+r.getProperty(key));
            }
//            r.setTemporalProperty("travel_time", 400, 88);
            r.getTemporalProperty("travel_time", 0, Integer.MAX_VALUE-4, new TemporalRangeQuery() {
                @Override
                public void setValueType(ValueContentType valueType) {
                    System.out.println(valueType);
                }

                @Override
                public void onNewEntry(InternalEntry entry) {
                    System.out.print(entry.getKey().getStartTime()+":["+entry.getKey().getValueType()+"]"+entry.getValue().toString());
                }

                @Override
                public Object onReturn() {
                    return null;
                }
            });
            tx.success();
        }
        System.out.println(System.currentTimeMillis() - t);
    }
```
结果为：
```
1392
30
30
30
30
30
30
30
30
30
30
30
30
30
30
30
null
null
null
null
null
null
null
null
null
null
null
null
null
null
null
null
null
null
null
null
null
null
null
null
null
null
null
null
null
null
null
null
null
null
null
null
null
null
null
null
null
null
null
null
null
null
null
null
null
null
null
null
null
null
null
null
null
null
null
null
null
null
null
null
null
null
null
null
null
null
null
null
null
null
null
null
null
null
null
null
null
null
null
null
null
2
2
1402
travel_time: 2%TGRAPH_TEMPORAL_PROPERTY
travel_time_1006: 36
travel_time_1007: 37
travel_time_1008: 38
travel_time_1009: 39
travel_time_1002: 32
travel_time_1003: 33
travel_time_1004: 34
travel_time_1005: 35
grid_id: 595640
chain_id: 30003
travel_time_1000: 30
travel_time_1001: 31
LONG



java.lang.NullPointerException
	at org.act.temporalProperty.helper.SameLevelMergeIterator.seek(SameLevelMergeIterator.java:83)
	at org.act.temporalProperty.helper.EPAppendIterator.seek(EPAppendIterator.java:43)
	at org.act.temporalProperty.table.TwoLevelMergeIterator.seek(TwoLevelMergeIterator.java:96)
	at org.act.temporalProperty.impl.UnknownToInvalidIterator.seek(UnknownToInvalidIterator.java:46)
	at org.act.temporalProperty.impl.TemporalPropertyStoreImpl.getRangeValue(TemporalPropertyStoreImpl.java:171)
	at org.neo4j.kernel.impl.store.TemporalPropertyStoreAdapter.getRange(TemporalPropertyStoreAdapter.java:109)
	at org.neo4j.kernel.impl.api.StateHandlingStatementOperations.tpQueryRange(StateHandlingStatementOperations.java:587)
	at org.neo4j.kernel.impl.api.StateHandlingStatementOperations.relationshipGetTemporalProperty(StateHandlingStatementOperations.java:527)
	at org.neo4j.kernel.impl.api.ConstraintEnforcingEntityOperations.relationshipGetTemporalProperty(ConstraintEnforcingEntityOperations.java:297)
	at org.neo4j.kernel.impl.api.OperationsFacade.relationshipGetTemporalProperty(OperationsFacade.java:524)
	at org.neo4j.kernel.impl.core.RelationshipProxy.getTemporalProperty(RelationshipProxy.java:353)
	at org.act.temporal.test.tcypher.WriteTemporalPropertyTest.tCypherTest(WriteTemporalPropertyTest.java:164)
```

**Comment by songjinghe** [comment]
锁定版本为 9422709ccc99aa8e78a8aa1979c4b687a82f55bc
temporal-neo4j版本为0e91323210ce224d29dd36459b1534ae8bea2599
public-test版本为0ba4fe18e799b369b7fa4b9c82663c8f108225bb

**Comment by songjinghe** [comment]
把SameLevelMergeIterator回退到0e88b1c8473888050326b7d1d9fd8f44c1b0558a版本（当时不知道怎么想的，同一级的多个文件（不同时间段）如果组合成一个iterator肯定那个迭代的顺序是要动态发生变化的啊。这是重大bug。然后这个错误没了又出来了新的错误，新开个issue处理。

**Comment by songjinghe** [comment]
如果是同一个entity的话就没问题了，因为现在Property在每个文件夹中是唯一的，而如果连entity也是唯一的话就只有时间一个增量了，就可以不用优先队列，用一个list就行。
