### ISSUE TITLE
写入时态属性报NullPointerException

### ISSUE THREAD

**Issue by songjinghe** [TGraphDB/temporal-storage#16]
```
java.lang.NullPointerException
        at org.act.temporalProperty.impl.MemTable$MemTableIterator.getNextEntry(MemTable.java:292)
        at org.act.temporalProperty.impl.MemTable$MemTableIterator.computeNext(MemTable.java:275)
        at org.act.temporalProperty.helper.AbstractSearchableIterator.tryToComputeNext(AbstractSearchableIterator.java:92)
        at org.act.temporalProperty.helper.AbstractSearchableIterator.hasNext(AbstractSearchableIterator.java:86)
        at org.act.temporalProperty.impl.UnknownToInvalidIterator.computeNext(UnknownToInvalidIterator.java:19)
        at org.act.temporalProperty.helper.AbstractSearchableIterator.tryToComputeNext(AbstractSearchableIterator.java:92)
        at org.act.temporalProperty.helper.AbstractSearchableIterator.hasNext(AbstractSearchableIterator.java:86)
        at org.act.temporalProperty.table.MergeProcess$MergeTask.runTask(MergeProcess.java:343)
        at org.act.temporalProperty.table.MergeProcess.startMergeProcess(MergeProcess.java:144)
        at org.act.temporalProperty.table.MergeProcess.run(MergeProcess.java:82)
```
写入代码是https://github.com/TGraphDB/TGraph-demo-test/tree/master/src/test/java/run/inner 文件夹中的`KernelWriteTemporalPropertyTest`和对应的`KernelWriteSocketServer`，版本`bf0599e`

**Comment by songjinghe** [comment]
代码捋了一遍，确实会产生这个结果，当在Memtable中迭代时遇到一个Unknown标记的记录。解决方法是直接返回这个Unknown的记录，之前为何需要一个lastEntry呢？
