### ISSUE TITLE
创建时态属性时报错

### ISSUE THREAD

**Issue by songjinghe** [TGraphDB/temporal-storage#17]
```
org.neo4j.graphdb.TransactionFailureException: Transaction was marked as successful, but unable to commit transaction so rolled back.
	at org.neo4j.kernel.TopLevelTransaction.close(TopLevelTransaction.java:122)
	at run.inner.KernelWriteSocketServer$KernelWriteExecutor.execute(KernelWriteSocketServer.java:79)
	at org.act.tgraph.demo.utils.TGraphSocketServer$ServerThread.run(TGraphSocketServer.java:182)
Caused by: org.neo4j.kernel.api.exceptions.TransactionFailureException: Could not apply the transaction to the store after written to log
	at org.neo4j.kernel.impl.api.TransactionRepresentationCommitProcess.applyToStore(TransactionRepresentationCommitProcess.java:105)
	at org.neo4j.kernel.impl.api.TransactionRepresentationCommitProcess.commit(TransactionRepresentationCommitProcess.java:58)
	at org.neo4j.kernel.impl.api.KernelTransactionImplementation.commit(KernelTransactionImplementation.java:624)
	at org.neo4j.kernel.impl.api.KernelTransactionImplementation.close(KernelTransactionImplementation.java:488)
	at org.neo4j.kernel.TopLevelTransaction.close(TopLevelTransaction.java:100)
	... 2 more
Caused by: org.act.temporalProperty.exception.TPSRuntimeException: create temporal property failed, exist propertynull with same id but diff type! (new type: LONG)
	at org.act.temporalProperty.impl.TemporalPropertyStoreImpl.createProperty(TemporalPropertyStoreImpl.java:256)
	at org.act.temporalProperty.impl.TemporalPropertyStoreImpl.setProperty(TemporalPropertyStoreImpl.java:271)
	at org.neo4j.kernel.impl.store.TemporalPropertyStoreAdapter.setValue(TemporalPropertyStoreAdapter.java:120)
	at org.neo4j.temporal.TemporalPropertyStoreHandler.visitRelationshipTemporalPropertyCommand(TemporalPropertyStoreHandler.java:52)
	at org.neo4j.kernel.impl.api.CommandApplierFacade.visitRelationshipTemporalPropertyCommand(CommandApplierFacade.java:145)
	at org.neo4j.kernel.impl.transaction.command.Command$RelationshipTemporalPropertyCommand.handle(Command.java:396)
	at org.neo4j.kernel.impl.api.CommandApplierFacade.visit(CommandApplierFacade.java:83)
	at org.neo4j.kernel.impl.api.CommandApplierFacade.visit(CommandApplierFacade.java:46)
	at org.neo4j.kernel.impl.transaction.log.PhysicalTransactionRepresentation.accept(PhysicalTransactionRepresentation.java:69)
	at org.neo4j.kernel.impl.api.TransactionRepresentationStoreApplier.apply(TransactionRepresentationStoreApplier.java:121)
	at org.neo4j.kernel.impl.api.TransactionRepresentationCommitProcess.applyToStore(TransactionRepresentationCommitProcess.java:100)
	... 6 more
org.neo4j.graphdb.TransactionFailureException: Failure to begin transaction
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacade.beginTx(GraphDatabaseFacade.java:316)
	at run.inner.KernelWriteSocketServer$KernelWriteExecutor.execute(KernelWriteSocketServer.java:67)
	at org.act.tgraph.demo.utils.TGraphSocketServer$ServerThread.run(TGraphSocketServer.java:182)
Caused by: org.neo4j.kernel.api.exceptions.TransactionFailureException: Kernel has encountered some problem, please perform necessary action (tx recovery/restart)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.neo4j.kernel.KernelHealth.assertHealthy(KernelHealth.java:62)
	at org.neo4j.kernel.impl.api.Kernel.newTransaction(Kernel.java:81)
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacade.beginTx(GraphDatabaseFacade.java:309)
	... 2 more
Caused by: org.act.temporalProperty.exception.TPSRuntimeException: create temporal property failed, exist propertynull with same id but diff type! (new type: LONG)
	at org.act.temporalProperty.impl.TemporalPropertyStoreImpl.createProperty(TemporalPropertyStoreImpl.java:256)
	at org.act.temporalProperty.impl.TemporalPropertyStoreImpl.createProperty(TemporalPropertyStoreImpl.java:251)
	at org.act.temporalProperty.impl.TemporalPropertyStoreImpl.setProperty(TemporalPropertyStoreImpl.java:271)
	at org.neo4j.kernel.impl.store.TemporalPropertyStoreAdapter.setValue(TemporalPropertyStoreAdapter.java:120)
	at org.neo4j.temporal.TemporalPropertyStoreHandler.visitRelationshipTemporalPropertyCommand(TemporalPropertyStoreHandler.java:52)
	at org.neo4j.kernel.impl.api.CommandApplierFacade.visitRelationshipTemporalPropertyCommand(CommandApplierFacade.java:145)
	at org.neo4j.kernel.impl.transaction.command.Command$RelationshipTemporalPropertyCommand.handle(Command.java:396)
	at org.neo4j.kernel.impl.api.CommandApplierFacade.visit(CommandApplierFacade.java:83)
	at org.neo4j.kernel.impl.api.CommandApplierFacade.visit(CommandApplierFacade.java:46)
	at org.neo4j.kernel.impl.transaction.log.PhysicalTransactionRepresentation.accept(PhysicalTransactionRepresentation.java:69)
	at org.neo4j.kernel.impl.api.TransactionRepresentationStoreApplier.apply(TransactionRepresentationStoreApplier.java:121)
	at org.neo4j.kernel.impl.api.TransactionRepresentationCommitProcess.applyToStore(TransactionRepresentationCommitProcess.java:100)
	at org.neo4j.kernel.impl.api.TransactionRepresentationCommitProcess.commit(TransactionRepresentationCommitProcess.java:58)
	at org.neo4j.kernel.impl.api.KernelTransactionImplementation.commit(KernelTransactionImplementation.java:624)
	at org.neo4j.kernel.impl.api.KernelTransactionImplementation.close(KernelTransactionImplementation.java:488)
	at org.neo4j.kernel.TopLevelTransaction.close(TopLevelTransaction.java:100)
	at run.inner.KernelWriteSocketServer$KernelWriteExecutor.execute(KernelWriteSocketServer.java:79)
	... 1 more
```

如题，基本上是说已经有一个了

**Comment by songjinghe** [comment]
PS这个是偶然错误，时有时无

**Comment by songjinghe** [comment]
又出现一次

**Comment by songjinghe** [comment]
偶然错误，今天开机第一次运行时出现。

**Comment by songjinghe** [comment]
```java
    public boolean createProperty( int propertyId, ValueContentType type )
    {
        meta.lock.lockExclusive();
        try {
            SinglePropertyStore prop = meta.proStores().get( propertyId );
            if ( prop == null ) {
                try {
                    PropertyMetaData pMeta = new PropertyMetaData( propertyId, type );
                    meta.addStore( propertyId, new SinglePropertyStore( pMeta, dbDir, cache, index ) );
                    meta.addProperty( pMeta );
                    return true;
                } catch ( Throwable ignore ) {
                    return false;
                }
            } else {
                PropertyMetaData pMeta = meta.getProperties().get( propertyId );
                if ( pMeta != null && pMeta.getType() == type ) {
                    // already exist, maybe in recovery. so just delete all property then create again.
                    deleteProperty( propertyId );
                    return createProperty( propertyId, type );
                } else {
                    throw new TPSRuntimeException( "create temporal property failed, exist property (type:"+(pMeta==null?null:pMeta.getType())+") with same id but diff type! (new type: "+type+")" );
                }
            }
        } finally {
            meta.lock.unlockExclusive();
        }
    }
```
出错部分代码

**Comment by songjinghe** [comment]
出错意味着`pMeta`是null，而`prop`不为null。这就很奇怪了，明明放的时候是meta和store都放进去了的，为何返回时有prop无meta？按理说这段被放在两个锁之间，不同线程访问时也不应该得到不同结果的。
