### ISSUE TITLE
运行Benchmark测试时居然报错

### ISSUE THREAD

**Issue by songjinghe** [TGraphDB/temporal-storage#19]
```
java.util.NoSuchElementException
        at org.act.temporalProperty.helper.AbstractSearchableIterator.next(AbstractSearchableIterator.java:127)
        at org.act.temporalProperty.helper.AbstractSearchableIterator.next(AbstractSearchableIterator.java:37)
        at org.act.temporalProperty.helper.SameLevelMergeIterator.computeNext(SameLevelMergeIterator.java:49)
        at org.act.temporalProperty.helper.AbstractSearchableIterator.tryToComputeNext(AbstractSearchableIterator.java:103)
        at org.act.temporalProperty.helper.AbstractSearchableIterator.hasNext(AbstractSearchableIterator.java:97)
        at org.act.temporalProperty.table.TwoLevelMergeIterator.computeNext(TwoLevelMergeIterator.java:89)
        at org.act.temporalProperty.helper.EPMergeIterator.computeNext(EPMergeIterator.java:32)
        at org.act.temporalProperty.helper.AbstractSearchableIterator.tryToComputeNext(AbstractSearchableIterator.java:103)
        at org.act.temporalProperty.helper.AbstractSearchableIterator.hasNext(AbstractSearchableIterator.java:97)
        at org.act.temporalProperty.helper.AbstractSearchableIterator.seekFloor(AbstractSearchableIterator.java:81)
        at org.act.temporalProperty.table.TwoLevelMergeIterator.seekFloor(TwoLevelMergeIterator.java:135)
        at org.act.temporalProperty.impl.UnknownToInvalidIterator.seekFloor(UnknownToInvalidIterator.java:47)
        at org.act.temporalProperty.impl.TemporalPropertyStoreImpl.getRangeValue(TemporalPropertyStoreImpl.java:173)
        at org.neo4j.kernel.impl.store.TemporalPropertyStoreAdapter.getRange(TemporalPropertyStoreAdapter.java:110)
        at org.neo4j.kernel.impl.api.StateHandlingStatementOperations.tpQueryRange(StateHandlingStatementOperations.java:587)
        at org.neo4j.kernel.impl.api.StateHandlingStatementOperations.relationshipGetTemporalProperty(StateHandlingStatementOperations.java:527)
        at org.neo4j.kernel.impl.api.ConstraintEnforcingEntityOperations.relationshipGetTemporalProperty(ConstraintEnforcingEntityOperations.java:297)
        at org.neo4j.kernel.impl.api.OperationsFacade.relationshipGetTemporalProperty(OperationsFacade.java:524)
        at org.neo4j.kernel.impl.core.RelationshipProxy.getTemporalProperty(RelationshipProxy.java:350)
        at edu.buaa.server.EarliestArriveTimeTGraphKernel.getEarliestArriveTime(EarliestArriveTimeTGraphKernel.java:53)
        at edu.buaa.algo.EarliestArriveTime.loopAllNeighborsUpdateArriveTime(EarliestArriveTime.java:58)
        at edu.buaa.algo.EarliestArriveTime.run(EarliestArriveTime.java:35)
        at edu.buaa.server.KernelTcpServer.execute(KernelTcpServer.java:138)
        at edu.buaa.server.KernelTcpServer.execute(KernelTcpServer.java:58)
        at edu.buaa.utils.TGraphSocketServer$ServerThread.run(TGraphSocketServer.java:179)
```

**Comment by songjinghe** [comment]
出错的road id是73918，时间段查询的开始时间是1272870771，截止时间是1272872394

**Comment by songjinghe** [comment]
奇怪的是居然在benchmark里面没有找到对应的EarliestArriveTimeAggrTx，这个就很奇怪了

**Comment by songjinghe** [comment]
写了一个测试来重现，结果又出现新的问题
```java
public class QuickTestSpin {

    @Test
    public void run(){
        GraphDatabaseService db = new GraphDatabaseFactory().newEmbeddedDatabase(new File("e:/tgraph/test-db"));
        try(Transaction tx = db.beginTx()){
            Relationship r = db.getRelationshipById(73918);
            r.getTemporalProperty("travel_time", Helper.time(1272870771), Helper.time(1272872394), new TemporalRangeQuery() {
                @Override
                public void setValueType(String valueType) {
                    System.out.println("set value type");
                }

                @Override
                public void onNewEntry(InternalEntry entry) {
                    System.out.println("on entry: "+entry.getKey().getStartTime());
                }

                @Override
                public Object onReturn() {
                    System.out.println("on return");
                    return null;
                }
            });
        }finally {
            db.shutdown();
        }
    }
}
```
结果报了另一个错：
```
java.lang.AssertionError: java.lang.IllegalArgumentException: invalid time value 2305843009213693950, only support 0 to 2305843009213693949

	at org.act.temporalProperty.query.TimePointL.<init>(TimePointL.java:44)
	at org.act.temporalProperty.impl.InternalKey.decode(InternalKey.java:162)
	at org.act.temporalProperty.impl.InternalKey.decode(InternalKey.java:168)
	at java.util.Comparator.lambda$comparing$77a9974f$1(Comparator.java:469)
	at org.act.temporalProperty.table.TableComparator.compare(TableComparator.java:34)
	at org.act.temporalProperty.table.TableComparator.compare(TableComparator.java:11)
	at org.act.temporalProperty.table.IndexBlockIterator.seek(IndexBlockIterator.java:75)
	at org.act.temporalProperty.table.TableIterator.seekInternal(TableIterator.java:54)
	at org.act.temporalProperty.table.TableIterator.seekInternal(TableIterator.java:26)
	at org.act.temporalProperty.util.AbstractSeekingIterator.seek(AbstractSeekingIterator.java:41)
	at org.act.temporalProperty.impl.PackInternalKeyIterator.seekFloor(PackInternalKeyIterator.java:38)
	at org.act.temporalProperty.table.TwoLevelMergeIterator.seekFloor(TwoLevelMergeIterator.java:134)
	at org.act.temporalProperty.helper.EPEntryIterator.seekToFirst(EPEntryIterator.java:28)
	at org.act.temporalProperty.helper.EPEntryIterator.<init>(EPEntryIterator.java:22)
	at org.act.temporalProperty.helper.EPAppendIterator.append(EPAppendIterator.java:26)
	at org.act.temporalProperty.impl.SinglePropertyStore.getRangeValueIter(SinglePropertyStore.java:111)
	at org.act.temporalProperty.impl.TemporalPropertyStoreImpl.getRangeValue(TemporalPropertyStoreImpl.java:162)
	at org.neo4j.kernel.impl.store.TemporalPropertyStoreAdapter.getRange(TemporalPropertyStoreAdapter.java:110)
	at org.neo4j.kernel.impl.api.StateHandlingStatementOperations.tpQueryRange(StateHandlingStatementOperations.java:587)
	at org.neo4j.kernel.impl.api.StateHandlingStatementOperations.relationshipGetTemporalProperty(StateHandlingStatementOperations.java:527)
	at org.neo4j.kernel.impl.api.ConstraintEnforcingEntityOperations.relationshipGetTemporalProperty(ConstraintEnforcingEntityOperations.java:297)
	at org.neo4j.kernel.impl.api.OperationsFacade.relationshipGetTemporalProperty(OperationsFacade.java:524)
	at org.neo4j.kernel.impl.core.RelationshipProxy.getTemporalProperty(RelationshipProxy.java:350)
	at run.QuickTestSpin.run(QuickTestSpin.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:69)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:48)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:292)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:157)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.IllegalArgumentException: invalid time value 2305843009213693950, only support 0 to 2305843009213693949
	... 46 more
```

**Comment by songjinghe** [comment]
看起来是把NOW的前一个time给写到了文件里。NOW的值只可能出现在filebuffer和日志及索引文件里可能有。memtable和主文件里都是没有的。而且NOW应该是不允许调用pre()函数的。所以这个值是哪里来的？重新debug了一次，发现是因为在stable文件里有INIT。而INIT的表示和time冲突了导致的。因为那个long类型的前3个bit被用来表示valueType，但是INIT表示为-2时默认会占用第一个bit，所以就冲突了。

**Comment by songjinghe** [comment]
解决的办法。这个问题发生在存储时，所以一个办法是取消INIT的存在，只允许从0开始。另一个办法是再拿出一个bit作为是否是INIT的表示，否则占用了3个bit就没法表示负数了。从实际情况来看，有一个INIT还是必要的。另一个办法就是在encode和decode上做文章，用LONG.MAX-1作为INIT，用LONG.MAX作为NOW。其他的值还照旧表示。所以范围是0到LONG.MAX-2。我看行。

**Comment by songjinghe** [comment]
改完这个又出错。这次是
```
Exception in thread "TCypher con 33" org.act.temporalProperty.exception.TPSNHException: iterators which ran out should not in heap!
	at org.act.temporalProperty.helper.SameLevelMergeIterator.lambda$static$0(SameLevelMergeIterator.java:24)
	at java.util.PriorityQueue.siftUpUsingComparator(PriorityQueue.java:670)
	at java.util.PriorityQueue.siftUp(PriorityQueue.java:646)
	at java.util.PriorityQueue.offer(PriorityQueue.java:345)
	at java.util.PriorityQueue.add(PriorityQueue.java:322)
	at org.act.temporalProperty.helper.SameLevelMergeIterator.computeNext(SameLevelMergeIterator.java:50)
	at org.act.temporalProperty.helper.AbstractSearchableIterator.tryToComputeNext(AbstractSearchableIterator.java:103)
	at org.act.temporalProperty.helper.AbstractSearchableIterator.hasNext(AbstractSearchableIterator.java:97)
	at org.act.temporalProperty.table.TwoLevelMergeIterator.computeNext(TwoLevelMergeIterator.java:30)
	at org.act.temporalProperty.helper.EPMergeIterator.computeNext(EPMergeIterator.java:32)
	at org.act.temporalProperty.helper.AbstractSearchableIterator.tryToComputeNext(AbstractSearchableIterator.java:103)
	at org.act.temporalProperty.helper.AbstractSearchableIterator.hasNext(AbstractSearchableIterator.java:97)
	at org.act.temporalProperty.impl.UnknownToInvalidIterator.computeNext(UnknownToInvalidIterator.java:19)
	at org.act.temporalProperty.helper.AbstractSearchableIterator.tryToComputeNext(AbstractSearchableIterator.java:103)
	at org.act.temporalProperty.helper.AbstractSearchableIterator.hasNext(AbstractSearchableIterator.java:97)
	at org.act.temporalProperty.impl.TemporalPropertyStoreImpl.getRangeValue(TemporalPropertyStoreImpl.java:175)
	at org.neo4j.kernel.impl.store.TemporalPropertyStoreAdapter.getRange(TemporalPropertyStoreAdapter.java:110)
	at org.neo4j.kernel.impl.api.StateHandlingStatementOperations.tpQueryRange(StateHandlingStatementOperations.java:587)
	at org.neo4j.kernel.impl.api.StateHandlingStatementOperations.relationshipGetTemporalProperty(StateHandlingStatementOperations.java:527)
	at org.neo4j.kernel.impl.api.ConstraintEnforcingEntityOperations.relationshipGetTemporalProperty(ConstraintEnforcingEntityOperations.java:297)
	at org.neo4j.kernel.impl.api.OperationsFacade.relationshipGetTemporalProperty(OperationsFacade.java:524)
	at org.neo4j.kernel.impl.core.RelationshipProxy.getTemporalProperty(RelationshipProxy.java:350)
	at edu.buaa.server.EarliestArriveTimeTGraphKernel.getEarliestArriveTime(EarliestArriveTimeTGraphKernel.java:56)
	at edu.buaa.algo.EarliestArriveTime.loopAllNeighborsUpdateArriveTime(EarliestArriveTime.java:58)
	at edu.buaa.algo.EarliestArriveTime.run(EarliestArriveTime.java:35)
	at edu.buaa.server.KernelTcpServer.execute(KernelTcpServer.java:138)
	at edu.buaa.server.KernelTcpServer.execute(KernelTcpServer.java:58)
	at edu.buaa.utils.TGraphSocketServer$ServerThread.run(TGraphSocketServer.java:179)
```

**Comment by songjinghe** [comment]
似乎已经fix了，上面的测试用例没有再报错。
