### ISSUE TITLE
恢复时报File is corrupt: size must be at least 48 bytes

### ISSUE THREAD

**Issue by songjinghe** [TGraphDB/temporal-storage#3]
理论上应该是任意时刻断电都能重新正常启动（虽然可能有数据丢失），但是现在启动时报一个File is corrupt: size must be at least 48 bytes的错误。查看一下UnStableFile的文件大小是0。
【如何重现】开启调试模式并在merge的时候设断点停下并退出，再次重启恢复时就会有这个问题。

**Comment by songjinghe** [comment]
现在发现在恢复的合并过程中会报这个错误，数据量很小，30多MB，在恢复完成后会有一次flush操作，这个flush会触发merge操作。这时候原来有数据的UnstableFile会被替换成了一个大小为0的文件，然后会报错。

**Comment by songjinghe** [comment]
在恢复之前查看了一下数据库的meta文件，如下：

```
################## unstable.meta #################
FileMetaData{number=0, fileSize=74, smallest=2147483647, largest=-1, allowedSeeks=1073741824}
FileMetaData{number=2, fileSize=19321220, smallest=0, largest=999, allowedSeeks=1073741824}

##### Warning: file not exist: /tmp/amitabha/dynNode/unstable.new.meta
################## stable.meta #################

##### Warning: file not exist: /tmp/amitabha/dynNode/stable.new.meta

```

**Comment by songjinghe** [comment]
@HuangHX 学长发现是由于dump了一个大小为0的MemTable导致的，解决方法是不合并无数据的MemTable。

**Comment by songjinghe** [comment]
问题依旧，这次是删掉了3号unstable文件，数据库损坏后的元信息如下：

```
################## unstable.meta #################
FileMetaData{number=0, fileSize=4828656, smallest=7648, largest=7822, allowedSeeks=1073741824}
FileMetaData{number=2, fileSize=18198239, smallest=6990, largest=7647, allowedSeeks=1073741824}
FileMetaData{number=3, fileSize=38664860, smallest=5592, largest=6989, allowedSeeks=1073741824}

##### Warning: file not exist: /tmp/amitabha/dynNode/unstable.new.meta
################## stable.meta #################
FileMetaData{number=0, fileSize=154696001, smallest=0, largest=5591, allowedSeeks=1073741824}

##### Warning: file not exist: /tmp/amitabha/dynNode/stable.new.meta
```

实际数据写入到7999，而且是在恢复完成后触发的merge操作中文件大小变成了0

**Comment by songjinghe** [comment]
问题解决，原因是在MergeProcess里面的merge方法里，第56行检测unstable文件的机制出了问题，改成：

``` java
for( Long fileNumber : new long[]{0,1,2,3,4} )
```

就好了

**Comment by songjinghe** [comment]
合并到stableFile的时候是不是也需要改成这样？

**Comment by songjinghe** [comment]
在测试stablefile的时候也报错：

```
Exception in thread "DynStore-Merge-Node" com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalArgumentException: File is corrupt: size must be at least 48 bytes
    at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2203)
    at com.google.common.cache.LocalCache.get(LocalCache.java:3937)
    at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3941)
    at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824)
    at org.act.dynproperty.impl.TableCache.getTable(TableCache.java:96)
    at org.act.dynproperty.impl.TableCache.newIterator(TableCache.java:78)
    at org.act.dynproperty.impl.StableLevel.getlastFileIterator(StableLevel.java:416)
    at org.act.dynproperty.table.MergeProcess.merge2StableFile(MergeProcess.java:206)
    at org.act.dynproperty.table.MergeProcess.merge(MergeProcess.java:63)
    at org.act.dynproperty.impl.UnstableLevel.startMergeProcess(UnstableLevel.java:511)
    at org.act.dynproperty.impl.UnstableLevel.access$200(UnstableLevel.java:37)
    at org.act.dynproperty.impl.UnstableLevel$1.run(UnstableLevel.java:102)
    at java.lang.Thread.run(Thread.java:745)
 Caused by: java.lang.IllegalArgumentException: File is corrupt: size must be at least 48 bytes
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
    at org.act.dynproperty.table.Table.<init>(Table.java:56)
    at org.act.dynproperty.table.MMapTable.<init>(MMapTable.java:50)
    at org.act.dynproperty.impl.TableCache$TableAndFile.<init>(TableCache.java:144)
    at org.act.dynproperty.impl.TableCache$TableAndFile.<init>(TableCache.java:126)
    at org.act.dynproperty.impl.TableCache$1.load(TableCache.java:56)
    at org.act.dynproperty.impl.TableCache$1.load(TableCache.java:51)
    at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
    at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2319)
    at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282)
    at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2197)
    ... 12 more
```

然后发现stablefile也被删掉成了一个大小为0的文件。。。很类似啊

**Comment by songjinghe** [comment]
发现问题的原因是在写入stablefile时会把上一个stablefile（比如`000003.st`）与它的stbuf（`000003.stbuf`）文件合并（在`StableLevel.addFile()`），此时会先生成一个合并后的`000005.dbtmp`文件，然后删掉`000003.st`和`000003.stbuf`文件，然后把`000005.dbtmp`文件改成`000003.st`文件。
如果断电发生在删掉`000003.st`以后，还没来得及给`000005.dbtmp`改名的时候，就凭空少了一个stableFile，但是metafile里仍然有这个stableFile的信息，所以在读取时会出错。在本例中是在恢复时，没有校验，写入到合并stableFile时出错了。
