### ISSUE TITLE
插入动态属性时报key must be greater than last key

### ISSUE THREAD

**Issue by songjinghe** [TGraphDB/temporal-storage#4]
RT

**Comment by songjinghe** [comment]
在写入数据库时发生了以下错误：
```
java.lang.AssertionError: key must be greater than last key, InternalKey{eid=120018 proId=3, time=1273593609, valueType=LONG} InternalKey{eid=120018 proId=3, time=1273593609, valueType=INVALID}
        at org.act.temporalProperty.table.TableBuilder.add(TableBuilder.java:148)
        at org.act.temporalProperty.table.MergeProcess$MergeTask.runTask(MergeProcess.java:348)
        at org.act.temporalProperty.table.MergeProcess.startMergeProcess(MergeProcess.java:144)
        at org.act.temporalProperty.table.MergeProcess.run(MergeProcess.java:82)
```
这个错误貌似之前也见过 #4 。初步怀疑是边界条件的问题。

**Comment by songjinghe** [comment]
先考虑能否重现类似的问题。可能有点难。试试。
——重现速度太慢，已经是用20个线程写了，考虑先搞Kernel的写，看看时间如何。

**Comment by songjinghe** [comment]
又捉到一次：
```
java.lang.AssertionError: key must be greater than last key, InternalKey{eid=120049 proId=3, time=1272652202, valueType=INVALID} InternalKey{eid=120049 proId=3, time=1272652202, valueType=LONG}
        at org.act.temporalProperty.table.TableBuilder.add(TableBuilder.java:148)
        at org.act.temporalProperty.table.MergeProcess$MergeTask.runTask(MergeProcess.java:348)
        at org.act.temporalProperty.table.MergeProcess.startMergeProcess(MergeProcess.java:144)
        at org.act.temporalProperty.table.MergeProcess.run(MergeProcess.java:82)
```

**Comment by songjinghe** [comment]
发现一个恐怖的事情，之前海星学长改leveldb的代码，我有一部分没有重写，然后那一部分的代码的功能和注释的不一样。。。好可怕的说。。。比如在
https://github.com/TGraphDB/temporal-storage/blob/8d77912c218e9ff42242152f44649edb128df00c/src/main/java/org/act/temporalProperty/table/BlockIterator.java#L140
和原始的代码https://github.com/dain/leveldb/blob/master/leveldb/src/main/java/org/iq80/leveldb/table/BlockIterator.java
对比一下就发现，这里的注释`change to search for first key less than or equal to targetKey`是海星学长的，而上面一行`linear search (within restart block) for first key greater than or equal to targetKey`是原来的，这两个功能完全不一样，如果不是仔细看代码我一直以为是后面的功能！！！然后好多都是按照这个写的。。。

**Comment by songjinghe** [comment]
这玩意要如何debug？之前是在每个iterator前面套一个debug用的iterator，似乎也可以，关键我是需要知道每个entry是从哪里来的，经过了哪些iterator。还是说这个东西最可能出现在两层合并的那个地方。其他的基本上似乎也不可能。

**Comment by songjinghe** [comment]
初步判断错误来自TwoLevelMergeIterator。目前错误依旧，TwoLevelMergeIterator的代码也不是非常直观，我认为这来自于我们对于文件的错误建模，也许文件读出来的结果就应该是基于时间区间的，仅在读和写的时候才转换为时间点。——当然这个也许明天早晨我就把它解决了也说不定。

**Comment by songjinghe** [comment]
用debugIterator找到一个不错的溯源方法，把每个Iterator都套上debug，然后在debugIterator中记录约4个迭代的结果。最后把所有debugiterator的历史记录都大约出来就能看到每个key是从哪里出来的了。

**Comment by songjinghe** [comment]
现在认为错误应该是来自于merge过程。这就是开始没错后面出错的原因。
原因应该是在merge的时候插入buffer是按时间区间写入的，如果文件的时间是[20,40]，写入的时间区间是[30,40]则会在buffer中插入30的点和41的点（UNKNOWN）这样就导致buffer中的时间点可能大于文件的时间。因此在SameLevelMergeIterator中会产生连续两个相同的key（其中一个可能是Unknown），解决的办法是如果写入的时间区间的末尾等于文件最大值的话，那么就不写入41那个点（也就是写到now）

但是我之前好像看到过连续两个都不是UNKNOWN的情况，那是什么鬼？

**Comment by songjinghe** [comment]
两个都不是UNKNOWN的是由于在TwoLevelMergeIterator中生成了相同的entry导致的。这个本身没有问题，问题在于insert到filebuffer的内容没有根据文件的时间写入到不同的filebuffer，而是只写入了一个filebuffer（哪怕这个时间区间跨了好几个文件）
