### ISSUE TITLE
读取动态属性时报null pointer exception

### ISSUE THREAD

**Issue by songjinghe** [TGraphDB/temporal-storage#5]
已经过了进一步确认，当事务中有删除动态属性的操作，然后紧接着有一个读取动态属性操作的时候就会报错。
输出（check是读取）

```
i:0 ...checking~i:0 ...checked OK, deleted~
i:1 ...checking~【此处报错】
```

错误

```
java.lang.NullPointerException
    at org.neo4j.kernel.impl.api.state.PropertyContainerState$Mutable.getDynProperties(PropertyContainerState.java:173)
    at org.neo4j.kernel.impl.api.state.TxState.addedNodeDynProperties(TxState.java:73)
    at org.neo4j.kernel.impl.api.StateHandlingStatementOperations.nodeGetProperty(StateHandlingStatementOperations.java:382)
    at org.neo4j.kernel.impl.api.ConstraintEnforcingEntityOperations.nodeGetProperty(ConstraintEnforcingEntityOperations.java:125)
    at org.neo4j.kernel.impl.api.OperationsFacade.nodeGetProperty(OperationsFacade.java:168)
    at org.neo4j.kernel.impl.core.NodeProxy.getDynPropertyPointValue(NodeProxy.java:267)
    at org.act.dyngraph.test.recovery.RecoveryDeleteIdempotentTest.phase2MakeBrokenDB(RecoveryDeleteIdempotentTest.java:85)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
```

**Comment by songjinghe** [comment]
@HuangHX 学长说在org/neo4j/kernel/impl/api/StateHandlingStatementOperations.java里面第383行左右的逻辑似乎有问题。待他解决。主要是以前使用场景中没有查询和删除在一起的情况。

**Comment by songjinghe** [comment]
这个问题在Demo中也发现了，时态最短路径里面，只有在事务中有对数据库进行修改的操作，后面的读取操作就会报错。

**Comment by songjinghe** [comment]
已修复，见 https://github.com/HuangLS/neo4j/commit/d8ac5ca3a6727f3f00f7f9e4acb134758b485e37
